---
# tasks for setting up the nginx reverse proxy

#- name: enable epel
#  yum: name=http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-2.noarch.rpm state=present

- name: install packages
  yum: name=nginx state=present enablerepo=epel
  sudo: yes

- name: Copy nginx configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  sudo: yes

- name: setup nginx host file dirs
  sudo: yes
  file: name=/etc/nginx/{{ item }} state=directory owner=root group=root
  with_items:
    - sites-available
    - sites-enabled

- name: Start and enable nginx
  service: name=nginx state=restarted enabled=yes
  sudo: yes
