---
nginx_user: nginx
nginx_pid: /run/nginx.pid
nginx_worker_processes: 1
nginx_worker_connections: 1024

nginx_server_log: "/var/log/nginx/{{app_name}}.log"
nginx_server_root: "/srv/{{app_name}}/"
nginx_server_index: index.php index.html index.htm
nginx_server_proxy_pass: "http://{{ app_name }}/"

nginx_upstream_name: "{{ app_name }}"

